provider:
  name: configdirector

resources:
  project:
    create:
      path: /projects
      method: POST
    read:
      path: /projects/{projectId}
      method: GET
    schema:
      ignores:
        - projectId
        - createdAt
        - updatedAt
        - environments.createdAt
        - environments.updatedAt

  environment:
    create:
      path: /projects/{projectId}/environments
      method: POST
    read:
      path: /projects/{projectId}/environments/{environmentId}
      method: GET
    update:
      path: /projects/{projectId}/environments/{environmentId}
      method: PUT
    schema:
      ignores:
        - environmentId
        - createdAt
        - updatedAt

  config:
    create:
      path: /projects/{projectId}/configs
      method: POST
    read:
      path: /projects/{projectId}/configs/{configKey}
      method: GET
    update:
      path: /projects/{projectId}/configs/{configKey}
      method: PATCH
    delete:
      path: /projects/{projectId}/configs/{configKey}
      method: DELETE
    schema:
      ignores:
        - configKey
        - defaultValue
        - typeOptions
        - targets
        - variations
        - createdAt
        - updatedAt

data_sources:
  project:
    read:
      path: /projects/{projectId}
      method: GET
    schema:
      ignores:
        - projectId
        - createdAt
        - updatedAt
        - environments.createdAt
        - environments.updatedAt

  projects:
    read:
      path: /projects
      method: GET
    schema:
      ignores:
        - createdAt
        - updatedAt
        - projects.createdAt
        - projects.updatedAt

  environment:
    read:
      path: /projects/{projectId}/environments/{environmentId}
      method: GET
    schema:
      ignores:
        - environmentId
        - createdAt
        - updatedAt

  environments:
    read:
      path: /projects/{projectId}/environments
      method: GET
    schema:
      ignores:
        - createdAt
        - updatedAt
        - environments.createdAt
        - environments.updatedAt

  config:
    read:
      path: /projects/{projectId}/configs/{configKey}
      method: GET
    schema:
      ignores:
        - configKey
        - defaultValue
        - typeOptions
        - targets
        - variations
        - createdAt
        - updatedAt

  configs:
    read:
      path: /projects/{projectId}/configs
      method: GET
    schema:
      ignores:
        - defaultValue
        - typeOptions
        - targets
        - variations
        - createdAt
        - updatedAt
        - configs.defaultValue
        - configs.typeOptions
        - configs.targets
        - configs.variations
        - configs.createdAt
        - configs.updatedAt
