terraform {
  required_providers {
    configdirector = {
      source  = "ConfigDirector/configdirector"
      version = "~> 0.2"
    }
  }
}

provider "configdirector" {}

# The same seed always derives the same UUID; different seeds derive
# different UUIDs. Used for configdirector_config_targeting_rules' rule/
# condition/percentage-bucket "id" fields, which the API requires but which
# can't be auto-generated by the provider - see that resource's example for
# rule_id() used in context.
output "example_rule_id" {
  value = provider::configdirector::rule_id("appversion-check")
}
