// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ConfigResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"client": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Default:  booldefault.StaticBool(true),
			},
			"deprecated_keys": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"config_id": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.StringAttribute{
							Computed: true,
						},
						"is_primary": schema.BoolAttribute{
							Computed: true,
						},
						"key": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: DeprecatedKeysType{
						ObjectType: types.ObjectType{
							AttrTypes: DeprecatedKeysValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.LengthAtMost(1000),
				},
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"key": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(4, 150),
				},
			},
			"lifetime": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"permanent",
						"temporary",
					),
				},
			},
			"project_id": schema.StringAttribute{
				Computed: true,
			},
			"role": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"config",
						"flag",
						"kill-switch",
						"experiment",
					),
				},
			},
			"server": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Default:  booldefault.StaticBool(true),
			},
			"state": schema.StringAttribute{
				Computed: true,
			},
			"type": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"boolean",
						"string",
						"integer",
						"float",
						"enum",
						"url",
						"json",
						"timespan",
					),
				},
			},
		},
	}
}

type ConfigModel struct {
	Client         types.Bool   `tfsdk:"client"`
	DeprecatedKeys types.List   `tfsdk:"deprecated_keys"`
	Description    types.String `tfsdk:"description"`
	Id             types.String `tfsdk:"id"`
	Key            types.String `tfsdk:"key"`
	Lifetime       types.String `tfsdk:"lifetime"`
	ProjectId      types.String `tfsdk:"project_id"`
	Role           types.String `tfsdk:"role"`
	Server         types.Bool   `tfsdk:"server"`
	State          types.String `tfsdk:"state"`
	Type           types.String `tfsdk:"type"`
}

var _ basetypes.ObjectTypable = DeprecatedKeysType{}

type DeprecatedKeysType struct {
	basetypes.ObjectType
}

func (t DeprecatedKeysType) Equal(o attr.Type) bool {
	other, ok := o.(DeprecatedKeysType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DeprecatedKeysType) String() string {
	return "DeprecatedKeysType"
}

func (t DeprecatedKeysType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	configIdAttribute, ok := attributes["config_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`config_id is missing from object`)

		return nil, diags
	}

	configIdVal, ok := configIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`config_id expected to be basetypes.StringValue, was: %T`, configIdAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	isPrimaryAttribute, ok := attributes["is_primary"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_primary is missing from object`)

		return nil, diags
	}

	isPrimaryVal, ok := isPrimaryAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_primary expected to be basetypes.BoolValue, was: %T`, isPrimaryAttribute))
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return nil, diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DeprecatedKeysValue{
		ConfigId:  configIdVal,
		Id:        idVal,
		IsPrimary: isPrimaryVal,
		Key:       keyVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewDeprecatedKeysValueNull() DeprecatedKeysValue {
	return DeprecatedKeysValue{
		state: attr.ValueStateNull,
	}
}

func NewDeprecatedKeysValueUnknown() DeprecatedKeysValue {
	return DeprecatedKeysValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDeprecatedKeysValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DeprecatedKeysValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DeprecatedKeysValue Attribute Value",
				"While creating a DeprecatedKeysValue value, a missing attribute value was detected. "+
					"A DeprecatedKeysValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DeprecatedKeysValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DeprecatedKeysValue Attribute Type",
				"While creating a DeprecatedKeysValue value, an invalid attribute value was detected. "+
					"A DeprecatedKeysValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DeprecatedKeysValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DeprecatedKeysValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DeprecatedKeysValue Attribute Value",
				"While creating a DeprecatedKeysValue value, an extra attribute value was detected. "+
					"A DeprecatedKeysValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DeprecatedKeysValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDeprecatedKeysValueUnknown(), diags
	}

	configIdAttribute, ok := attributes["config_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`config_id is missing from object`)

		return NewDeprecatedKeysValueUnknown(), diags
	}

	configIdVal, ok := configIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`config_id expected to be basetypes.StringValue, was: %T`, configIdAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewDeprecatedKeysValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	isPrimaryAttribute, ok := attributes["is_primary"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_primary is missing from object`)

		return NewDeprecatedKeysValueUnknown(), diags
	}

	isPrimaryVal, ok := isPrimaryAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_primary expected to be basetypes.BoolValue, was: %T`, isPrimaryAttribute))
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return NewDeprecatedKeysValueUnknown(), diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	if diags.HasError() {
		return NewDeprecatedKeysValueUnknown(), diags
	}

	return DeprecatedKeysValue{
		ConfigId:  configIdVal,
		Id:        idVal,
		IsPrimary: isPrimaryVal,
		Key:       keyVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewDeprecatedKeysValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DeprecatedKeysValue {
	object, diags := NewDeprecatedKeysValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDeprecatedKeysValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DeprecatedKeysType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDeprecatedKeysValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDeprecatedKeysValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDeprecatedKeysValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDeprecatedKeysValueMust(DeprecatedKeysValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DeprecatedKeysType) ValueType(ctx context.Context) attr.Value {
	return DeprecatedKeysValue{}
}

var _ basetypes.ObjectValuable = DeprecatedKeysValue{}

type DeprecatedKeysValue struct {
	ConfigId  basetypes.StringValue `tfsdk:"config_id"`
	Id        basetypes.StringValue `tfsdk:"id"`
	IsPrimary basetypes.BoolValue   `tfsdk:"is_primary"`
	Key       basetypes.StringValue `tfsdk:"key"`
	state     attr.ValueState
}

func (v DeprecatedKeysValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["config_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["is_primary"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["key"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.ConfigId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["config_id"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.IsPrimary.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["is_primary"] = val

		val, err = v.Key.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["key"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DeprecatedKeysValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DeprecatedKeysValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DeprecatedKeysValue) String() string {
	return "DeprecatedKeysValue"
}

func (v DeprecatedKeysValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"config_id":  basetypes.StringType{},
		"id":         basetypes.StringType{},
		"is_primary": basetypes.BoolType{},
		"key":        basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"config_id":  v.ConfigId,
			"id":         v.Id,
			"is_primary": v.IsPrimary,
			"key":        v.Key,
		})

	return objVal, diags
}

func (v DeprecatedKeysValue) Equal(o attr.Value) bool {
	other, ok := o.(DeprecatedKeysValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ConfigId.Equal(other.ConfigId) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.IsPrimary.Equal(other.IsPrimary) {
		return false
	}

	if !v.Key.Equal(other.Key) {
		return false
	}

	return true
}

func (v DeprecatedKeysValue) Type(ctx context.Context) attr.Type {
	return DeprecatedKeysType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DeprecatedKeysValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"config_id":  basetypes.StringType{},
		"id":         basetypes.StringType{},
		"is_primary": basetypes.BoolType{},
		"key":        basetypes.StringType{},
	}
}
