// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ConfigsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"configs": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"client": schema.BoolAttribute{
							Computed: true,
						},
						"deprecated_keys": schema.ListNestedAttribute{
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"config_id": schema.StringAttribute{
										Computed: true,
									},
									"id": schema.StringAttribute{
										Computed: true,
									},
									"is_primary": schema.BoolAttribute{
										Computed: true,
									},
									"key": schema.StringAttribute{
										Computed: true,
									},
								},
								CustomType: ConfigsDsDeprecatedKeysType{
									ObjectType: types.ObjectType{
										AttrTypes: ConfigsDsDeprecatedKeysValue{}.AttributeTypes(ctx),
									},
								},
							},
							Computed: true,
						},
						"description": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.StringAttribute{
							Computed: true,
						},
						"key": schema.StringAttribute{
							Computed: true,
						},
						"lifetime": schema.StringAttribute{
							Computed: true,
						},
						"project_id": schema.StringAttribute{
							Computed: true,
						},
						"role": schema.StringAttribute{
							Computed: true,
						},
						"server": schema.BoolAttribute{
							Computed: true,
						},
						"state": schema.StringAttribute{
							Computed: true,
						},
						"type": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: ConfigsType{
						ObjectType: types.ObjectType{
							AttrTypes: ConfigsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"project_id": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type ConfigsModel struct {
	Configs   types.Set    `tfsdk:"configs"`
	ProjectId types.String `tfsdk:"project_id"`
}

var _ basetypes.ObjectTypable = ConfigsType{}

type ConfigsType struct {
	basetypes.ObjectType
}

func (t ConfigsType) Equal(o attr.Type) bool {
	other, ok := o.(ConfigsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ConfigsType) String() string {
	return "ConfigsType"
}

func (t ConfigsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	clientAttribute, ok := attributes["client"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`client is missing from object`)

		return nil, diags
	}

	clientVal, ok := clientAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`client expected to be basetypes.BoolValue, was: %T`, clientAttribute))
	}

	deprecatedKeysAttribute, ok := attributes["deprecated_keys"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`deprecated_keys is missing from object`)

		return nil, diags
	}

	deprecatedKeysVal, ok := deprecatedKeysAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`deprecated_keys expected to be basetypes.ListValue, was: %T`, deprecatedKeysAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return nil, diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	lifetimeAttribute, ok := attributes["lifetime"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`lifetime is missing from object`)

		return nil, diags
	}

	lifetimeVal, ok := lifetimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`lifetime expected to be basetypes.StringValue, was: %T`, lifetimeAttribute))
	}

	projectIdAttribute, ok := attributes["project_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`project_id is missing from object`)

		return nil, diags
	}

	projectIdVal, ok := projectIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`project_id expected to be basetypes.StringValue, was: %T`, projectIdAttribute))
	}

	roleAttribute, ok := attributes["role"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role is missing from object`)

		return nil, diags
	}

	roleVal, ok := roleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role expected to be basetypes.StringValue, was: %T`, roleAttribute))
	}

	serverAttribute, ok := attributes["server"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`server is missing from object`)

		return nil, diags
	}

	serverVal, ok := serverAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`server expected to be basetypes.BoolValue, was: %T`, serverAttribute))
	}

	stateAttribute, ok := attributes["state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state is missing from object`)

		return nil, diags
	}

	stateVal, ok := stateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state expected to be basetypes.StringValue, was: %T`, stateAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ConfigsValue{
		Client:         clientVal,
		DeprecatedKeys: deprecatedKeysVal,
		Description:    descriptionVal,
		Id:             idVal,
		Key:            keyVal,
		Lifetime:       lifetimeVal,
		ProjectId:      projectIdVal,
		Role:           roleVal,
		Server:         serverVal,
		State:          stateVal,
		ConfigsType:    typeVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewConfigsValueNull() ConfigsValue {
	return ConfigsValue{
		state: attr.ValueStateNull,
	}
}

func NewConfigsValueUnknown() ConfigsValue {
	return ConfigsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewConfigsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ConfigsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ConfigsValue Attribute Value",
				"While creating a ConfigsValue value, a missing attribute value was detected. "+
					"A ConfigsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ConfigsValue Attribute Type",
				"While creating a ConfigsValue value, an invalid attribute value was detected. "+
					"A ConfigsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ConfigsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ConfigsValue Attribute Value",
				"While creating a ConfigsValue value, an extra attribute value was detected. "+
					"A ConfigsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ConfigsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewConfigsValueUnknown(), diags
	}

	clientAttribute, ok := attributes["client"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`client is missing from object`)

		return NewConfigsValueUnknown(), diags
	}

	clientVal, ok := clientAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`client expected to be basetypes.BoolValue, was: %T`, clientAttribute))
	}

	deprecatedKeysAttribute, ok := attributes["deprecated_keys"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`deprecated_keys is missing from object`)

		return NewConfigsValueUnknown(), diags
	}

	deprecatedKeysVal, ok := deprecatedKeysAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`deprecated_keys expected to be basetypes.ListValue, was: %T`, deprecatedKeysAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewConfigsValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewConfigsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return NewConfigsValueUnknown(), diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	lifetimeAttribute, ok := attributes["lifetime"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`lifetime is missing from object`)

		return NewConfigsValueUnknown(), diags
	}

	lifetimeVal, ok := lifetimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`lifetime expected to be basetypes.StringValue, was: %T`, lifetimeAttribute))
	}

	projectIdAttribute, ok := attributes["project_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`project_id is missing from object`)

		return NewConfigsValueUnknown(), diags
	}

	projectIdVal, ok := projectIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`project_id expected to be basetypes.StringValue, was: %T`, projectIdAttribute))
	}

	roleAttribute, ok := attributes["role"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role is missing from object`)

		return NewConfigsValueUnknown(), diags
	}

	roleVal, ok := roleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role expected to be basetypes.StringValue, was: %T`, roleAttribute))
	}

	serverAttribute, ok := attributes["server"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`server is missing from object`)

		return NewConfigsValueUnknown(), diags
	}

	serverVal, ok := serverAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`server expected to be basetypes.BoolValue, was: %T`, serverAttribute))
	}

	stateAttribute, ok := attributes["state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state is missing from object`)

		return NewConfigsValueUnknown(), diags
	}

	stateVal, ok := stateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state expected to be basetypes.StringValue, was: %T`, stateAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewConfigsValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewConfigsValueUnknown(), diags
	}

	return ConfigsValue{
		Client:         clientVal,
		DeprecatedKeys: deprecatedKeysVal,
		Description:    descriptionVal,
		Id:             idVal,
		Key:            keyVal,
		Lifetime:       lifetimeVal,
		ProjectId:      projectIdVal,
		Role:           roleVal,
		Server:         serverVal,
		State:          stateVal,
		ConfigsType:    typeVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewConfigsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ConfigsValue {
	object, diags := NewConfigsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewConfigsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ConfigsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewConfigsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewConfigsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewConfigsValueMust(ConfigsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ConfigsType) ValueType(ctx context.Context) attr.Value {
	return ConfigsValue{}
}

var _ basetypes.ObjectValuable = ConfigsValue{}

type ConfigsValue struct {
	Client         basetypes.BoolValue   `tfsdk:"client"`
	DeprecatedKeys basetypes.ListValue   `tfsdk:"deprecated_keys"`
	Description    basetypes.StringValue `tfsdk:"description"`
	Id             basetypes.StringValue `tfsdk:"id"`
	Key            basetypes.StringValue `tfsdk:"key"`
	Lifetime       basetypes.StringValue `tfsdk:"lifetime"`
	ProjectId      basetypes.StringValue `tfsdk:"project_id"`
	Role           basetypes.StringValue `tfsdk:"role"`
	Server         basetypes.BoolValue   `tfsdk:"server"`
	State          basetypes.StringValue `tfsdk:"state"`
	ConfigsType    basetypes.StringValue `tfsdk:"type"`
	state          attr.ValueState
}

func (v ConfigsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 11)

	var val tftypes.Value
	var err error

	attrTypes["client"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["deprecated_keys"] = basetypes.ListType{
		ElemType: ConfigsDsDeprecatedKeysValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["key"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["lifetime"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["project_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["role"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["server"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["state"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 11)

		val, err = v.Client.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["client"] = val

		val, err = v.DeprecatedKeys.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["deprecated_keys"] = val

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Key.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["key"] = val

		val, err = v.Lifetime.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["lifetime"] = val

		val, err = v.ProjectId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["project_id"] = val

		val, err = v.Role.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["role"] = val

		val, err = v.Server.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["server"] = val

		val, err = v.State.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["state"] = val

		val, err = v.ConfigsType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ConfigsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ConfigsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ConfigsValue) String() string {
	return "ConfigsValue"
}

func (v ConfigsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	deprecatedKeys := types.ListValueMust(
		ConfigsDsDeprecatedKeysType{
			basetypes.ObjectType{
				AttrTypes: ConfigsDsDeprecatedKeysValue{}.AttributeTypes(ctx),
			},
		},
		v.DeprecatedKeys.Elements(),
	)

	if v.DeprecatedKeys.IsNull() {
		deprecatedKeys = types.ListNull(
			ConfigsDsDeprecatedKeysType{
				basetypes.ObjectType{
					AttrTypes: ConfigsDsDeprecatedKeysValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.DeprecatedKeys.IsUnknown() {
		deprecatedKeys = types.ListUnknown(
			ConfigsDsDeprecatedKeysType{
				basetypes.ObjectType{
					AttrTypes: ConfigsDsDeprecatedKeysValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	attributeTypes := map[string]attr.Type{
		"client": basetypes.BoolType{},
		"deprecated_keys": basetypes.ListType{
			ElemType: ConfigsDsDeprecatedKeysValue{}.Type(ctx),
		},
		"description": basetypes.StringType{},
		"id":          basetypes.StringType{},
		"key":         basetypes.StringType{},
		"lifetime":    basetypes.StringType{},
		"project_id":  basetypes.StringType{},
		"role":        basetypes.StringType{},
		"server":      basetypes.BoolType{},
		"state":       basetypes.StringType{},
		"type":        basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"client":          v.Client,
			"deprecated_keys": deprecatedKeys,
			"description":     v.Description,
			"id":              v.Id,
			"key":             v.Key,
			"lifetime":        v.Lifetime,
			"project_id":      v.ProjectId,
			"role":            v.Role,
			"server":          v.Server,
			"state":           v.State,
			"type":            v.ConfigsType,
		})

	return objVal, diags
}

func (v ConfigsValue) Equal(o attr.Value) bool {
	other, ok := o.(ConfigsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Client.Equal(other.Client) {
		return false
	}

	if !v.DeprecatedKeys.Equal(other.DeprecatedKeys) {
		return false
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Key.Equal(other.Key) {
		return false
	}

	if !v.Lifetime.Equal(other.Lifetime) {
		return false
	}

	if !v.ProjectId.Equal(other.ProjectId) {
		return false
	}

	if !v.Role.Equal(other.Role) {
		return false
	}

	if !v.Server.Equal(other.Server) {
		return false
	}

	if !v.State.Equal(other.State) {
		return false
	}

	if !v.ConfigsType.Equal(other.ConfigsType) {
		return false
	}

	return true
}

func (v ConfigsValue) Type(ctx context.Context) attr.Type {
	return ConfigsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ConfigsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"client": basetypes.BoolType{},
		"deprecated_keys": basetypes.ListType{
			ElemType: ConfigsDsDeprecatedKeysValue{}.Type(ctx),
		},
		"description": basetypes.StringType{},
		"id":          basetypes.StringType{},
		"key":         basetypes.StringType{},
		"lifetime":    basetypes.StringType{},
		"project_id":  basetypes.StringType{},
		"role":        basetypes.StringType{},
		"server":      basetypes.BoolType{},
		"state":       basetypes.StringType{},
		"type":        basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = ConfigsDsDeprecatedKeysType{}

type ConfigsDsDeprecatedKeysType struct {
	basetypes.ObjectType
}

func (t ConfigsDsDeprecatedKeysType) Equal(o attr.Type) bool {
	other, ok := o.(ConfigsDsDeprecatedKeysType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ConfigsDsDeprecatedKeysType) String() string {
	return "ConfigsDsDeprecatedKeysType"
}

func (t ConfigsDsDeprecatedKeysType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	configIdAttribute, ok := attributes["config_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`config_id is missing from object`)

		return nil, diags
	}

	configIdVal, ok := configIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`config_id expected to be basetypes.StringValue, was: %T`, configIdAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	isPrimaryAttribute, ok := attributes["is_primary"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_primary is missing from object`)

		return nil, diags
	}

	isPrimaryVal, ok := isPrimaryAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_primary expected to be basetypes.BoolValue, was: %T`, isPrimaryAttribute))
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return nil, diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ConfigsDsDeprecatedKeysValue{
		ConfigId:  configIdVal,
		Id:        idVal,
		IsPrimary: isPrimaryVal,
		Key:       keyVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewConfigsDsDeprecatedKeysValueNull() ConfigsDsDeprecatedKeysValue {
	return ConfigsDsDeprecatedKeysValue{
		state: attr.ValueStateNull,
	}
}

func NewConfigsDsDeprecatedKeysValueUnknown() ConfigsDsDeprecatedKeysValue {
	return ConfigsDsDeprecatedKeysValue{
		state: attr.ValueStateUnknown,
	}
}

func NewConfigsDsDeprecatedKeysValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ConfigsDsDeprecatedKeysValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ConfigsDsDeprecatedKeysValue Attribute Value",
				"While creating a ConfigsDsDeprecatedKeysValue value, a missing attribute value was detected. "+
					"A ConfigsDsDeprecatedKeysValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigsDsDeprecatedKeysValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ConfigsDsDeprecatedKeysValue Attribute Type",
				"While creating a ConfigsDsDeprecatedKeysValue value, an invalid attribute value was detected. "+
					"A ConfigsDsDeprecatedKeysValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigsDsDeprecatedKeysValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ConfigsDsDeprecatedKeysValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ConfigsDsDeprecatedKeysValue Attribute Value",
				"While creating a ConfigsDsDeprecatedKeysValue value, an extra attribute value was detected. "+
					"A ConfigsDsDeprecatedKeysValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ConfigsDsDeprecatedKeysValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewConfigsDsDeprecatedKeysValueUnknown(), diags
	}

	configIdAttribute, ok := attributes["config_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`config_id is missing from object`)

		return NewConfigsDsDeprecatedKeysValueUnknown(), diags
	}

	configIdVal, ok := configIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`config_id expected to be basetypes.StringValue, was: %T`, configIdAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewConfigsDsDeprecatedKeysValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	isPrimaryAttribute, ok := attributes["is_primary"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_primary is missing from object`)

		return NewConfigsDsDeprecatedKeysValueUnknown(), diags
	}

	isPrimaryVal, ok := isPrimaryAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_primary expected to be basetypes.BoolValue, was: %T`, isPrimaryAttribute))
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return NewConfigsDsDeprecatedKeysValueUnknown(), diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	if diags.HasError() {
		return NewConfigsDsDeprecatedKeysValueUnknown(), diags
	}

	return ConfigsDsDeprecatedKeysValue{
		ConfigId:  configIdVal,
		Id:        idVal,
		IsPrimary: isPrimaryVal,
		Key:       keyVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewConfigsDsDeprecatedKeysValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ConfigsDsDeprecatedKeysValue {
	object, diags := NewConfigsDsDeprecatedKeysValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewConfigsDsDeprecatedKeysValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ConfigsDsDeprecatedKeysType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewConfigsDsDeprecatedKeysValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewConfigsDsDeprecatedKeysValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigsDsDeprecatedKeysValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewConfigsDsDeprecatedKeysValueMust(ConfigsDsDeprecatedKeysValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ConfigsDsDeprecatedKeysType) ValueType(ctx context.Context) attr.Value {
	return ConfigsDsDeprecatedKeysValue{}
}

var _ basetypes.ObjectValuable = ConfigsDsDeprecatedKeysValue{}

type ConfigsDsDeprecatedKeysValue struct {
	ConfigId  basetypes.StringValue `tfsdk:"config_id"`
	Id        basetypes.StringValue `tfsdk:"id"`
	IsPrimary basetypes.BoolValue   `tfsdk:"is_primary"`
	Key       basetypes.StringValue `tfsdk:"key"`
	state     attr.ValueState
}

func (v ConfigsDsDeprecatedKeysValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["config_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["is_primary"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["key"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.ConfigId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["config_id"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.IsPrimary.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["is_primary"] = val

		val, err = v.Key.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["key"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ConfigsDsDeprecatedKeysValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ConfigsDsDeprecatedKeysValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ConfigsDsDeprecatedKeysValue) String() string {
	return "ConfigsDsDeprecatedKeysValue"
}

func (v ConfigsDsDeprecatedKeysValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"config_id":  basetypes.StringType{},
		"id":         basetypes.StringType{},
		"is_primary": basetypes.BoolType{},
		"key":        basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"config_id":  v.ConfigId,
			"id":         v.Id,
			"is_primary": v.IsPrimary,
			"key":        v.Key,
		})

	return objVal, diags
}

func (v ConfigsDsDeprecatedKeysValue) Equal(o attr.Value) bool {
	other, ok := o.(ConfigsDsDeprecatedKeysValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ConfigId.Equal(other.ConfigId) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.IsPrimary.Equal(other.IsPrimary) {
		return false
	}

	if !v.Key.Equal(other.Key) {
		return false
	}

	return true
}

func (v ConfigsDsDeprecatedKeysValue) Type(ctx context.Context) attr.Type {
	return ConfigsDsDeprecatedKeysType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ConfigsDsDeprecatedKeysValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"config_id":  basetypes.StringType{},
		"id":         basetypes.StringType{},
		"is_primary": basetypes.BoolType{},
		"key":        basetypes.StringType{},
	}
}
