// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func ConfigdirectorProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type ConfigdirectorModel struct {
}
