package provider

import (
	"context"

	"github.com/google/uuid"
	"github.com/hashicorp/terraform-plugin-framework/function"
)

var _ function.Function = &RuleIDFunction{}

// ruleIDNamespace is an arbitrary fixed UUID used as the namespace for
// deriving rule ids via uuid.NewSHA1 (UUID v5): what matters is only that
// it's constant, not what it is, since v5 UUIDs are namespace+seed -> id.
var ruleIDNamespace = uuid.MustParse("2c5ba338-2b3e-4f0a-9a3f-2f2f6f6a6b3d")

func NewRuleIDFunction() function.Function {
	return &RuleIDFunction{}
}

// RuleIDFunction backs provider::configdirector::rule_id(seed). It exists
// because configdirector_config_targeting_rules' "rules" attribute requires
// every rule/condition/percentage-bucket to carry a client-supplied UUID id.
type RuleIDFunction struct{}

func (f *RuleIDFunction) Metadata(ctx context.Context, req function.MetadataRequest, resp *function.MetadataResponse) {
	resp.Name = "rule_id"
}

func (f *RuleIDFunction) Definition(ctx context.Context, req function.DefinitionRequest, resp *function.DefinitionResponse) {
	resp.Definition = function.Definition{
		Summary: "Derives a stable UUID from a seed string.",
		Description: "Returns a deterministic UUID derived from the given seed string: the same seed always " +
			"produces the same UUID, and different seeds produce different UUIDs. Intended for " +
			"configdirector_config_targeting_rules' rule/condition/percentage-bucket \"id\" fields, which the API " +
			"requires but which can't be auto-generated by the provider. Pick any short, meaningful, stable name " +
			"per entry, e.g. rule_id(\"appversion-check\").",
		Parameters: []function.Parameter{
			function.StringParameter{
				Name:        "seed",
				Description: "Any string. The same seed always derives the same UUID.",
			},
		},
		Return: function.StringReturn{},
	}
}

func (f *RuleIDFunction) Run(ctx context.Context, req function.RunRequest, resp *function.RunResponse) {
	var seed string
	resp.Error = function.ConcatFuncErrors(resp.Error, req.Arguments.Get(ctx, &seed))
	if resp.Error != nil {
		return
	}

	id := uuid.NewSHA1(ruleIDNamespace, []byte(seed)).String()
	resp.Error = function.ConcatFuncErrors(resp.Error, resp.Result.Set(ctx, id))
}
