name: Build and Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency: build-and-test
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: 1.26.5

      - name: Build
        run: make build

      - name: Test
        run: make test
